const API = (window.APP_CONFIG?.API_BASE_URL || "").replace(/\/$/, "");
const app = document.querySelector("#app");
const state = { classes: [], teachers: [], students: [] };
const title = { classes: "Classes", teachers: "Teachers", students: "Students" };
const plural = { classes: "classes", teachers: "teachers", students: "students" };
const singular = { classes: "Class", teachers: "Teacher", students: "Student" };

async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json" }, ...options });
  if (response.status === 204) return null;
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || "Request failed.");
  return data;
}
function toast(message) { const element = document.querySelector("#toast"); element.textContent = message; element.classList.add("show"); setTimeout(() => element.classList.remove("show"), 3200); }
function status(value) { return `<span class="status ${value.toLowerCase().replaceAll(" ", "-")}">${value}</span>`; }
function escape(value = "") { return String(value).replace(/[&<>"']/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" })[character]); }
async function load() { [state.classes, state.teachers, state.students] = await Promise.all([request("/api/classes"), request("/api/teachers"), request("/api/students")]); }
function route() { return location.hash.slice(1) || "dashboard"; }
function navButton(kind) { return `<button class="button" data-action="new" data-kind="${kind}">Add ${singular[kind]}</button>`; }
function renderDashboard() {
  const activeStudents = state.students.filter((student) => student.status === "Active").length;
  const byClass = state.classes.map((item) => `<p>${escape(item.class_name)} <small>${item.student_count} student${item.student_count === 1 ? "" : "s"}</small></p>`).join("") || "<p>No classes yet.</p>";
  app.innerHTML = `<div class="page-heading"><div><p class="eyebrow">School records</p><h1>A calm view of the day.</h1><p>Keep classes, teachers, and families in step.</p></div></div><section class="stats"><div class="stat"><b>${state.classes.length}</b><span>Classes</span></div><div class="stat"><b>${state.teachers.length}</b><span>Teachers</span></div><div class="stat"><b>${state.students.length}</b><span>Students</span></div></section><section class="detail"><section><h2>${activeStudents} active students</h2><p>Current enrolments across all classes.</p></section><section><h2>Students by class</h2>${byClass}</section></section>`;
}
function renderList(kind, classFilter = "") {
  const rows = kind === "students" && classFilter ? state.students.filter((item) => item.class_id === classFilter) : state[kind];
  const headings = kind === "classes" ? ["Code", "Class", "Teacher", "Students", "Status"] : kind === "teachers" ? ["Code", "Teacher", "Specialty", "Classes", "Status"] : ["Code", "Student", "Class", "Guardian", "Status"];
  const cells = (item) => kind === "classes" ? [item.class_code, item.class_name, item.teacher_name || "Unassigned", item.student_count, status(item.status)] : kind === "teachers" ? [item.teacher_code, item.full_name, item.subject_specialty || "-", item.class_names?.join(", ") || "Unassigned", status(item.status)] : [item.student_code, item.full_name, item.class_name, item.guardian_name || "-", status(item.status)];
  const classFilterControl = kind === "students" ? `<select id="classFilter" aria-label="Filter students by class"><option value="">All classes</option>${state.classes.map((item) => `<option value="${item.class_id}" ${item.class_id === classFilter ? "selected" : ""}>${escape(item.class_name)}</option>`).join("")}</select>` : "";
  app.innerHTML = `<div class="page-heading"><div><p class="eyebrow">Records</p><h1>${title[kind]}</h1><p>Search, update, or remove school records.</p></div>${navButton(kind)}</div><div class="toolbar"><input class="search" id="search" placeholder="Search ${plural[kind]}" aria-label="Search ${plural[kind]}">${classFilterControl}<span>${rows.length} total</span></div><div class="table-wrap"><table><thead><tr>${headings.map((heading) => `<th>${heading}</th>`).join("")}<th>Actions</th></tr></thead><tbody id="records">${rows.map((item) => `<tr data-search="${escape(cells(item).join(" ")).toLowerCase()}">${cells(item).map((cell) => `<td>${cell}</td>`).join("")}<td class="actions">${kind === "classes" ? `<button class="icon-button" data-action="detail" data-id="${item.class_id}" title="View class details">View</button>` : ""}<button class="icon-button" data-action="edit" data-kind="${kind}" data-id="${item[`${kind.slice(0, -1)}_id`]}" title="Edit">Edit</button><button class="icon-button" data-action="delete" data-kind="${kind}" data-id="${item[`${kind.slice(0, -1)}_id`]}" title="Delete">Delete</button></td></tr>`).join("") || `<tr><td colspan="6" class="empty">No records found.</td></tr>`}</tbody></table></div>`;
  document.querySelector("#search").addEventListener("input", (event) => document.querySelectorAll("#records tr[data-search]").forEach((row) => row.hidden = !row.dataset.search.includes(event.target.value.toLowerCase())));
  document.querySelector("#classFilter")?.addEventListener("change", (event) => renderList("students", event.target.value));
}
function renderDetail(id) { const item = state.classes.find((entry) => entry.class_id === id); if (!item) return renderList("classes"); const students = state.students.filter((student) => student.class_id === id); app.innerHTML = `<div class="page-heading"><div><p class="eyebrow">Class detail</p><h1>${escape(item.class_name)}</h1><p>${escape(item.class_code)} · ${escape(item.subjects || "No subjects recorded")}</p></div><button class="button secondary" data-action="back">Back to classes</button></div><div class="detail"><section><h2>Teaching details</h2><p><b>Teacher:</b> ${escape(item.teacher_name || "Unassigned")}</p><p><b>Schedule:</b> ${escape(item.schedule_days || "-")} ${escape(item.schedule_time || "")}</p><p><b>Room:</b> ${escape(item.room || "-")}</p></section><section><h2>Students (${students.length})</h2><button class="icon-button" data-action="export" data-id="${item.class_id}" title="Export students to CSV">Export CSV</button>${students.map((student) => `<p>${escape(student.full_name)} <small>${escape(student.student_code)}</small></p>`).join("") || "<p>No students enrolled.</p>"}</section></div>`; }
function input(label, name, value = "", type = "text", options = "") { const isRequired = label.includes("*"); return `<label>${label}${options ? `<select name="${name}" ${isRequired ? "required" : ""}>${options}</select>` : `<input type="${type}" name="${name}" value="${escape(value)}" ${isRequired ? "required" : ""}>`}</label>`; }
function options(items, selected, value, label, blank = "Select...") { return `<option value="">${blank}</option>${items.map((item) => `<option value="${item[value]}" ${item[value] === selected ? "selected" : ""}>${escape(item[label])}</option>`).join("")}`; }
function openForm(kind, record = {}) {
  const idKey = `${kind.slice(0, -1)}_id`; const isEdit = Boolean(record[idKey]);
  let fields = kind === "classes" ? [input("Class code *", "class_code", record.class_code), input("Class name *", "class_name", record.class_name), input("Teacher", "teacher_id", "", "text", options(state.teachers, record.teacher_id, "teacher_id", "full_name", "Unassigned")), input("Status", "status", "", "text", options([{value:"Active"},{value:"Inactive"}], record.status, "value", "value")), input("Subjects", "subjects", record.subjects), input("Schedule days", "schedule_days", record.schedule_days), input("Schedule time", "schedule_time", record.schedule_time), input("Room", "room", record.room)] : kind === "teachers" ? [input("Teacher code *", "teacher_code", record.teacher_code), input("Full name *", "full_name", record.full_name), input("Email *", "email", record.email, "email"), input("Phone", "phone", record.phone), input("Subject specialty", "subject_specialty", record.subject_specialty), input("Join date", "join_date", record.join_date?.slice(0, 10), "date"), input("Status", "status", "", "text", options([{value:"Active"},{value:"On Leave"},{value:"Inactive"}], record.status, "value", "value"))] : [input("Student code *", "student_code", record.student_code), input("Full name *", "full_name", record.full_name), input("Class *", "class_id", "", "text", options(state.classes, record.class_id, "class_id", "class_name")), input("Gender", "gender", "", "text", options([{value:"M"},{value:"F"}], record.gender, "value", "value", "Select...")), input("Age", "age", record.age, "number"), input("Guardian name", "guardian_name", record.guardian_name), input("Guardian phone", "guardian_phone", record.guardian_phone), input("Guardian email", "guardian_email", record.guardian_email, "email"), input("Enrolment date", "enrolment_date", record.enrolment_date?.slice(0, 10), "date"), input("Status", "status", "", "text", options([{value:"Active"},{value:"Withdrawn"}], record.status, "value", "value"))];
  const dialog = document.createElement("dialog"); dialog.innerHTML = `<div class="modal-head"><h2>${isEdit ? "Edit" : "Add"} ${singular[kind]}</h2><button class="icon-button" data-close>Close</button></div><form class="record-form"><div class="form-grid">${fields.join("")}</div><div class="modal-actions"><button type="button" class="button secondary" data-close>Cancel</button><button class="button">Save</button></div></form>`; document.body.append(dialog); dialog.showModal();
  dialog.querySelectorAll("[data-close]").forEach((button) => button.onclick = () => dialog.close()); dialog.addEventListener("close", () => dialog.remove());
  const classSelect = dialog.querySelector("select[name=class_id]"); if (classSelect) classSelect.addEventListener("change", () => { if (!isEdit) { const code = state.classes.find((item) => item.class_id === classSelect.value)?.class_code; const existing = state.students.filter((item) => item.class_id === classSelect.value).map((item) => Number(item.student_code.match(/student(\d+)$/)?.[1]) || 0); const next = Math.max(0, ...existing) + 1; dialog.querySelector("[name=student_code]").value = code ? `${code}-student${String(next).padStart(2, "0")}` : ""; } });
  dialog.querySelector("form").onsubmit = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.target)); try { await request(`/api/${kind}${isEdit ? `/${record[idKey]}` : ""}`, { method: isEdit ? "PUT" : "POST", body: JSON.stringify(data) }); dialog.close(); await refresh(); toast(`${title[kind].slice(0, -1)} saved.`); } catch (error) { toast(error.message); } };
}
async function remove(kind, id) { if (!confirm(`Delete this ${singular[kind].toLowerCase()}?`)) return; try { await request(`/api/${kind}/${id}`, { method: "DELETE" }); await refresh(); toast("Record deleted."); } catch (error) { toast(error.message); } }
function exportStudentsCsv(classId) { const rows = state.students.filter((item) => item.class_id === classId); const header = "student_code,full_name,gender,age,guardian_name,guardian_phone,guardian_email,status"; const body = rows.map((item) => [item.student_code, item.full_name, item.gender, item.age, item.guardian_name, item.guardian_phone, item.guardian_email, item.status].map((value) => `"${String(value ?? "").replaceAll('"', '""')}"`).join(",")).join("\n"); const blob = new Blob([`${header}\n${body}`], { type: "text/csv" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${state.classes.find((item) => item.class_id === classId)?.class_code || "class"}-students.csv`; link.click(); URL.revokeObjectURL(link.href); }
async function refresh() { app.innerHTML = `<div class="loading">Loading school records...</div>`; try { await load(); const current = route(); current === "dashboard" ? renderDashboard() : current.startsWith("class/") ? renderDetail(current.split("/")[1]) : renderList(current); } catch (error) { app.innerHTML = `<div class="empty"><h1>Could not load records</h1><p>${escape(error.message)} The service may be waking up. Try again in a moment.</p><button class="button" data-action="retry">Retry</button></div>`; } }
document.addEventListener("click", (event) => { const button = event.target.closest("button[data-action]"); if (!button) return; const { action, kind, id } = button.dataset; if (action === "new") openForm(kind); if (action === "edit") openForm(kind, state[kind].find((item) => item[`${kind.slice(0, -1)}_id`] === id)); if (action === "delete") remove(kind, id); if (action === "detail") location.hash = `class/${id}`; if (action === "back") location.hash = "classes"; if (action === "retry") refresh(); if (action === "export") exportStudentsCsv(id); });
window.addEventListener("hashchange", refresh); refresh();
